// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using serenity.Infrastructure.Data;

#nullable disable

namespace serenity.Infrastructure.Migrations
{
    [DbContext(typeof(SerenityDbContext))]
    partial class SerenityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("serenity.Infrastructure.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date")
                        .HasColumnName("appointment_date");

                    b.Property<TimeOnly>("AppointmentTime")
                        .HasColumnType("time")
                        .HasColumnName("appointment_time");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("integer")
                        .HasColumnName("psychologist_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Pendiente'");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PatientId" }, "patient_id");

                    b.HasIndex(new[] { "PsychologistId" }, "psychologist_id");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("serenity.Infrastructure.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsFromPsychologist")
                        .HasColumnType("boolean")
                        .HasColumnName("is_from_psychologist");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_text");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("integer")
                        .HasColumnName("psychologist_id");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("read_at");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PatientId" }, "patient_id")
                        .HasDatabaseName("patient_id1");

                    b.HasIndex(new[] { "PsychologistId" }, "psychologist_id")
                        .HasDatabaseName("psychologist_id1");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("serenity.Infrastructure.DailyMood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<short>("Mood")
                        .HasColumnType("smallint")
                        .HasColumnName("mood");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PatientId", "Date" }, "patient_id")
                        .IsUnique()
                        .HasDatabaseName("patient_id2");

                    b.ToTable("daily_moods", (string)null);
                });

            modelBuilder.Entity("serenity.Infrastructure.EmotionalState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("EmotionalState1")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("emotional_state");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<decimal?>("Value")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PatientId" }, "patient_id")
                        .HasDatabaseName("patient_id3");

                    b.ToTable("emotional_states", (string)null);
                });

            modelBuilder.Entity("serenity.Infrastructure.InsightsAndRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<string>("Priority")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<int?>("PsychologistId")
                        .HasColumnType("integer")
                        .HasColumnName("psychologist_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PatientId" }, "patient_id")
                        .HasDatabaseName("patient_id4");

                    b.HasIndex(new[] { "PsychologistId" }, "psychologist_id")
                        .HasDatabaseName("psychologist_id2");

                    b.ToTable("insights_and_recommendations", (string)null);
                });

            modelBuilder.Entity("serenity.Infrastructure.MeditationSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date")
                        .HasColumnName("session_date");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PatientId" }, "patient_id")
                        .HasDatabaseName("patient_id5");

                    b.ToTable("meditation_sessions", (string)null);
                });

            modelBuilder.Entity("serenity.Infrastructure.MentalWellbeingMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short?>("ConcentrationLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("concentration_level");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<short?>("EnergyLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("energy_level");

                    b.Property<int?>("MeditationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("meditation_minutes")
                        .HasDefaultValueSql("0");

                    b.Property<int?>("MeditationSessions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("meditation_sessions")
                        .HasDefaultValueSql("0");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<short?>("SatisfactionLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("satisfaction_level");

                    b.Property<decimal?>("SleepDuration")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("sleep_duration");

                    b.Property<string>("SleepQuality")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sleep_quality");

                    b.Property<short?>("StressLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("stress_level");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PatientId" }, "patient_id")
                        .HasDatabaseName("patient_id6");

                    b.ToTable("mental_wellbeing_metrics", (string)null);
                });

            modelBuilder.Entity("serenity.Infrastructure.MoodMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AnxiousPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("anxious_percentage");

                    b.Property<decimal?>("CalmPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("calm_percentage");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<decimal?>("HappyPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("happy_percentage");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<decimal?>("SadPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("sad_percentage");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PatientId" }, "patient_id")
                        .HasDatabaseName("patient_id7");

                    b.ToTable("mood_metrics", (string)null);
                });

            modelBuilder.Entity("serenity.Infrastructure.NoteSuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("NoteId")
                        .HasColumnType("integer")
                        .HasColumnName("note_id");

                    b.Property<string>("Suggestion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("suggestion");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "NoteId" }, "note_id");

                    b.ToTable("note_suggestions", (string)null);
                });

            modelBuilder.Entity("serenity.Infrastructure.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("text")
                        .HasColumnName("diagnosis");

                    b.Property<string>("Diseases")
                        .HasColumnType("text")
                        .HasColumnName("diseases");

                    b.Property<string>("InitialObjective")
                        .HasColumnType("text")
                        .HasColumnName("initial_objective");

                    b.Property<string>("MedicalAdvice")
                        .HasColumnType("text")
                        .HasColumnName("medical_advice");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int?>("PsychologistId")
                        .HasColumnType("integer")
                        .HasColumnName("psychologist_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Activo'");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PsychologistId" }, "psychologist_id")
                        .HasDatabaseName("psychologist_id3");

                    b.HasIndex(new[] { "UserId" }, "user_id")
                        .IsUnique();

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("serenity.Infrastructure.PatientNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiDiagnosis")
                        .HasColumnType("text")
                        .HasColumnName("ai_diagnosis");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<short>("Mood")
                        .HasColumnType("smallint")
                        .HasColumnName("mood");

                    b.Property<bool?>("NeedsFollowUp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("needs_follow_up")
                        .HasDefaultValueSql("0");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("integer")
                        .HasColumnName("psychologist_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PatientId" }, "patient_id")
                        .HasDatabaseName("patient_id8");

                    b.HasIndex(new[] { "PsychologistId" }, "psychologist_id")
                        .HasDatabaseName("psychologist_id4");

                    b.ToTable("patient_notes", (string)null);
                });

            modelBuilder.Entity("serenity.Infrastructure.PatientReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnxietyLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("anxiety_level");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("diagnosis");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("integer")
                        .HasColumnName("psychologist_id");

                    b.Property<string>("Recommendations")
                        .HasColumnType("text")
                        .HasColumnName("recommendations");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PatientId" }, "patient_id")
                        .HasDatabaseName("patient_id9");

                    b.HasIndex(new[] { "PsychologistId" }, "psychologist_id")
                        .HasDatabaseName("psychologist_id5");

                    b.ToTable("patient_reports", (string)null);
                });

            modelBuilder.Entity("serenity.Infrastructure.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Dosage")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dosage");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Frequency")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("frequency");

                    b.Property<string>("Instructions")
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("medication_name");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("integer")
                        .HasColumnName("psychologist_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Activa'");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PatientId" }, "patient_id")
                        .HasDatabaseName("patient_id10");

                    b.HasIndex(new[] { "PsychologistId" }, "psychologist_id")
                        .HasDatabaseName("psychologist_id6");

                    b.ToTable("prescriptions", (string)null);
                });

            modelBuilder.Entity("serenity.Infrastructure.Psychologist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CollegeNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("college_number");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location");

                    b.Property<string>("Specialization")
                        .HasColumnType("text")
                        .HasColumnName("specialization");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int?>("WeeklyScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("weekly_score")
                        .HasDefaultValueSql("0");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CollegeNumber" }, "college_number")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "user_id")
                        .IsUnique()
                        .HasDatabaseName("user_id1");

                    b.ToTable("psychologists", (string)null);
                });

            modelBuilder.Entity("serenity.Infrastructure.StressLevelsByTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<short>("StressLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("stress_level");

                    b.Property<TimeOnly>("TimeOfDay")
                        .HasColumnType("time")
                        .HasColumnName("time_of_day");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PatientId" }, "patient_id")
                        .HasDatabaseName("patient_id11");

                    b.ToTable("stress_levels_by_time", (string)null);
                });

            modelBuilder.Entity("serenity.Infrastructure.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Specialization")
                        .HasColumnType("text")
                        .HasColumnName("specialization");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "user_id")
                        .IsUnique()
                        .HasDatabaseName("user_id2");

                    b.ToTable("trainers", (string)null);
                });

            modelBuilder.Entity("serenity.Infrastructure.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text")
                        .HasColumnName("google_id");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("1");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("serenity.Infrastructure.Appointment", b =>
                {
                    b.HasOne("serenity.Infrastructure.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("appointments_ibfk_1");

                    b.HasOne("serenity.Infrastructure.Psychologist", "Psychologist")
                        .WithMany("Appointments")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("appointments_ibfk_2");

                    b.Navigation("Patient");

                    b.Navigation("Psychologist");
                });

            modelBuilder.Entity("serenity.Infrastructure.ChatMessage", b =>
                {
                    b.HasOne("serenity.Infrastructure.Patient", "Patient")
                        .WithMany("ChatMessages")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("chat_messages_ibfk_1");

                    b.HasOne("serenity.Infrastructure.Psychologist", "Psychologist")
                        .WithMany("ChatMessages")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("chat_messages_ibfk_2");

                    b.Navigation("Patient");

                    b.Navigation("Psychologist");
                });

            modelBuilder.Entity("serenity.Infrastructure.DailyMood", b =>
                {
                    b.HasOne("serenity.Infrastructure.Patient", "Patient")
                        .WithMany("DailyMoods")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("daily_moods_ibfk_1");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("serenity.Infrastructure.EmotionalState", b =>
                {
                    b.HasOne("serenity.Infrastructure.Patient", "Patient")
                        .WithMany("EmotionalStates")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("emotional_states_ibfk_1");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("serenity.Infrastructure.InsightsAndRecommendation", b =>
                {
                    b.HasOne("serenity.Infrastructure.Patient", "Patient")
                        .WithMany("InsightsAndRecommendations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("insights_and_recommendations_ibfk_1");

                    b.HasOne("serenity.Infrastructure.Psychologist", "Psychologist")
                        .WithMany("InsightsAndRecommendations")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("insights_and_recommendations_ibfk_2");

                    b.Navigation("Patient");

                    b.Navigation("Psychologist");
                });

            modelBuilder.Entity("serenity.Infrastructure.MeditationSession", b =>
                {
                    b.HasOne("serenity.Infrastructure.Patient", "Patient")
                        .WithMany("MeditationSessions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("meditation_sessions_ibfk_1");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("serenity.Infrastructure.MentalWellbeingMetric", b =>
                {
                    b.HasOne("serenity.Infrastructure.Patient", "Patient")
                        .WithMany("MentalWellbeingMetrics")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("mental_wellbeing_metrics_ibfk_1");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("serenity.Infrastructure.MoodMetric", b =>
                {
                    b.HasOne("serenity.Infrastructure.Patient", "Patient")
                        .WithMany("MoodMetrics")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("mood_metrics_ibfk_1");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("serenity.Infrastructure.NoteSuggestion", b =>
                {
                    b.HasOne("serenity.Infrastructure.PatientNote", "Note")
                        .WithMany("NoteSuggestions")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("note_suggestions_ibfk_1");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("serenity.Infrastructure.Patient", b =>
                {
                    b.HasOne("serenity.Infrastructure.Psychologist", "Psychologist")
                        .WithMany("Patients")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("patients_ibfk_2");

                    b.HasOne("serenity.Infrastructure.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("serenity.Infrastructure.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("patients_ibfk_1");

                    b.Navigation("Psychologist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("serenity.Infrastructure.PatientNote", b =>
                {
                    b.HasOne("serenity.Infrastructure.Patient", "Patient")
                        .WithMany("PatientNotes")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("patient_notes_ibfk_1");

                    b.HasOne("serenity.Infrastructure.Psychologist", "Psychologist")
                        .WithMany("PatientNotes")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("patient_notes_ibfk_2");

                    b.Navigation("Patient");

                    b.Navigation("Psychologist");
                });

            modelBuilder.Entity("serenity.Infrastructure.PatientReport", b =>
                {
                    b.HasOne("serenity.Infrastructure.Patient", "Patient")
                        .WithMany("PatientReports")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("patient_reports_ibfk_1");

                    b.HasOne("serenity.Infrastructure.Psychologist", "Psychologist")
                        .WithMany("PatientReports")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("patient_reports_ibfk_2");

                    b.Navigation("Patient");

                    b.Navigation("Psychologist");
                });

            modelBuilder.Entity("serenity.Infrastructure.Prescription", b =>
                {
                    b.HasOne("serenity.Infrastructure.Patient", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("prescriptions_ibfk_1");

                    b.HasOne("serenity.Infrastructure.Psychologist", "Psychologist")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("prescriptions_ibfk_2");

                    b.Navigation("Patient");

                    b.Navigation("Psychologist");
                });

            modelBuilder.Entity("serenity.Infrastructure.Psychologist", b =>
                {
                    b.HasOne("serenity.Infrastructure.User", "User")
                        .WithOne("Psychologist")
                        .HasForeignKey("serenity.Infrastructure.Psychologist", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("psychologists_ibfk_1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("serenity.Infrastructure.StressLevelsByTime", b =>
                {
                    b.HasOne("serenity.Infrastructure.Patient", "Patient")
                        .WithMany("StressLevelsByTimes")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("stress_levels_by_time_ibfk_1");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("serenity.Infrastructure.Trainer", b =>
                {
                    b.HasOne("serenity.Infrastructure.User", "User")
                        .WithOne("Trainer")
                        .HasForeignKey("serenity.Infrastructure.Trainer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("trainers_ibfk_1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("serenity.Infrastructure.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ChatMessages");

                    b.Navigation("DailyMoods");

                    b.Navigation("EmotionalStates");

                    b.Navigation("InsightsAndRecommendations");

                    b.Navigation("MeditationSessions");

                    b.Navigation("MentalWellbeingMetrics");

                    b.Navigation("MoodMetrics");

                    b.Navigation("PatientNotes");

                    b.Navigation("PatientReports");

                    b.Navigation("Prescriptions");

                    b.Navigation("StressLevelsByTimes");
                });

            modelBuilder.Entity("serenity.Infrastructure.PatientNote", b =>
                {
                    b.Navigation("NoteSuggestions");
                });

            modelBuilder.Entity("serenity.Infrastructure.Psychologist", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ChatMessages");

                    b.Navigation("InsightsAndRecommendations");

                    b.Navigation("PatientNotes");

                    b.Navigation("PatientReports");

                    b.Navigation("Patients");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("serenity.Infrastructure.User", b =>
                {
                    b.Navigation("Patient");

                    b.Navigation("Psychologist");

                    b.Navigation("Trainer");
                });
#pragma warning restore 612, 618
        }
    }
}
